name: Launch Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      release_name: 
        required: true
        type: string
      server_host: 
        required: true
        type: string
      server_port: 
        required: true
        type: string
      server_tls: 
        required: true
        type: boolean

    secrets:
      SERVER_SIGN_KEY:
        required: true
        
jobs:
  create-release:
    uses: ./.github/workflows/common-create-release.yml
    with:
      tag: ${{ inputs.tag }} 
      release_name: ${{ inputs.release_name }}
      server_host: ${{ inputs.server_host }}
      server_port: ${{ inputs.server_port }}
      server_tls: ${{ inputs.server_tls }}
    secrets: 
       SERVER_SIGN_KEY: ${{ secrets.SERVER_SIGN_KEY }}
